- src/Bempatrimoniado.php
- src/Graduacao.php
- src/Pessoa.php
- src/Posgraduacao.php
Fix #6 :+1: 
Testado no Ms SQL Server.
> Removido DBMAINT. das consultas

- src/Graduacao.php
> Adicionei o parâmetro $strFiltro no método ativos

- src/Graduacao.php
- src/Pessoa.php
Fix #19
Utilizado o método fonetico da classe Uteis
Classe Graduacao, método ativos
Classe Pessoa, método nomeFonetico
> Implementada busca fonética por pessoa

- README.md
- src/Graduacao.php
Fix #32
nomeCurso($codcur)
nomeHabilitacao($codhab, $codcur)
> Adicionado novos métodos na classe Graduacao

- README.md
- src/Graduacao.php
> Adicionei o método obterCursosHabilitacoes na classe Graduacao

- README.md
- src/Graduacao.php
> Adicionado o método obterDisciplinas

- README.md
- src/Graduacao.php
> Adicionado o método nomeDisciplina

- README.md
> Adicionando markdown para php no Readme

- src/Graduacao.php
> Modificados os métodos obterDisciplina e nomeDisciplina para que traga sempre a versão mais recente da disciplina

- README.md
> Adicionadas as informações do método programa ao readme.md

- README.md
- src/Graduacao.php
> Adicionado o método disciplinasConcluidas na classe Graduacao

- .gitignore
- composer.json
- composer.lock
- src/DB.php
- src/Pessoa.php
criado classe Log
alterando a classe Pessoa e Log
Na classe Pessoa mudando todos os métodos para não ser
mais estaticos e na classe Log colocando para receber
o parametro da class-name.
retirando comentários
alterado o nome do arquivo de log
corrigindo o log
várias mudanças efetuadas
deletado a classe Log
retornando os métodos da classe Pessoa para static
retirando o log da classe Pessoa, bem como o try catch
adicioando a classe Monolog na classe DB e fazendo o
try catch nos métodos fetch e fetchAll, bem como fazendo
o log de erros.
Fix #12 Fix #13
> adicionado o pacote monolog

- composer.json
- src/DB.php
Retirando o require da classe DB
Fix #61
> Corrigindo o composer.json

- src/Graduacao.php
- src/Posgraduacao.php
- src/Uteis.php
> removendo csv e filtrando ativos

- src/Pessoa.php
Criei um método único para designados:
Fix #70 
Fix #69 
Método que retorna vínculos:
Fix #68
> Implementa método que retorna vínculos

- src/Bempatrimoniado.php
- src/Graduacao.php
- src/Posgraduacao.php
Removidos trechos de código que faziam basicamente isso:
```php
$return = false
if($condicao){
$return = true
}
return $return
```
Fixes #74
> New returns

- src/Pessoa.php
> Usando o convert no módulo Pessoa

- README.md
- src/DB.php
fix #81 
Criado a variável ( REPLICADO_PATHLOG ) para configuração do caminho do log do replicado.
> corrigindo o problema do log do replicado

- README.md
- src/Pessoa.php
A função totalVinculo retorna o total de vínculo
ativo na unidade, ela recebe dois parâmetros:
vinculo - tipo de vínculo por extenso
unidade - codigo da unidade
Alterado o Readme para explicar a função tipoVinculo
fix #84
> adicionado nova função na classe Pessoa

- README.md
- src/Pessoa.php
Criado a consulta totalPosNivelPrograma que recebe dois parâmetros:
nivpgm e código da unidade
Ele retorna o total de aluno de pós matriculados de acordo com o nível
solicitado, exemplo:
ME = Mestrado
DO = Doutorado
DD = Doutorado Direto
Fix #86
> adicionado nova consulta

- README.md
- src/Graduacao.php
> Fix #88 - Adicionado novo método creditosDisciplina()

- src/Pessoa.php
Utilizado a classe Uteis para converter o resultado da consulta
para utf8.
Fix #92
> Corrigido a consulta

- src/Graduacao.php
> Fix #97 - Adicionada a função convert para corrigir o datatype nas consultas

- src/Graduacao.php
> Fix #99 - Corrigido convert na consulta para programa

- README.md
- src/Graduacao.php
>  Fix #111 Disciplinas equivalentes

- README.md
- src/Posgraduacao.php
> Fix #116 - Adicionado método trazer os programas de Pós-Graduação

- README.md
- src/Posgraduacao.php
> Fix #118 - Retorna apenas o programa de Pós quando solicitado

- src/Posgraduacao.php
> Fix #120 - Adicionada condição para trazer somente os programas de Pós ativos

- .gitignore
- README.md
- src/Posgraduacao.php
Retorna as áreas de concentração ativas dos programas de pós-graduação da unidade.
Se informado o código do curso (programa), retorna apenas as áreas deste curso.
> Retorna áreas de concentração dos programas de pós-graduação.

- README.md
- src/Pessoa.php
Para obter o nome diretamente sem usar dump.
> Retorna o nome completo a partir do codpes

- .gitignore
- README.md
- doc/contrib.md
- test/posgraduacao/alunosPrograma.php
- test/posgraduacao/areasPrograma.php
- test/posgraduacao/ativos.php
- test/posgraduacao/catalogoDisciplinas.php
- test/posgraduacao/disciplina.php
- test/posgraduacao/disciplinasOferecimento.php
- test/posgraduacao/oferecimento.php
- test/posgraduacao/orientadores.php
- test/posgraduacao/programas.php
- test/posgraduacao/verifica.php
- test/run.php
Aqui só criei os arquivos de testes para a classe posgraduacao. Tem várias coisinhas menores para arrumar mas já deve funcionar.
> fix #161 Rotinas de testes

- README.md
- src/Posgraduacao.php
- método para obter alunos de pós por programa e área de pós
- documentação do método
- dei uma linha entre os itens da documentação conforme conversado anteriormente
> Fix #145 alunos por programa de pós

- README.md
- src/Bempatrimoniado.php
> Adiciona opção de colunas em dump do patrimônio

- README.md
- src/Bempatrimoniado.php
- src/DB.php
Criado método bens($filtros = [], $buscas = [], $tipos = [])
Alterado método ativos($filtros = [], $buscas = [], $tipos = [])
Adicionado documentação no REAME.md
> Fix #171 Alteração/melhorias no método Bempatrimoniado->ativos

- src/Posgraduacao.php
Pois no nosso site o coordenador quer colocar o ano de ingresso dos alunos ativos.
> fix # 176 Em alunosPrograma retornar o ano de ingresso

- src/Posgraduacao.php
> Lista de Ministrantes por ordem alfabética de nome

- README.md
- src/Bempatrimoniado.php
Adicionado mais um parâmetro para limitar quantidade de registros, com
valor padrão 2000.
> Fix #173 Adicionar limite para busca nos bens patrimoniados

- src/Pessoa.php
> Fix #30 - Corrigindo charset do método Pessoa::totalVinculo

- README.md
- src/Pessoa.php
Fix #66 e #73 - Unificado em um novo método, porém acredito que tem aplicações que ainda usem os métodos antigos
> Fix #187 - Adicionado no readme as informações sobre os novos métodos

- README.md
- src/Pessoa.php
> Fix #189 - Adicionado Docente Aposentado em tiposVinculos e ativosVinculo

- README.md
- src/Graduacao.php
> Fix #191 - Novo método na Graduação para trazer o Departamento de Ensino do Aluno

- src/DB.php
- src/Pessoa.php
> Fix #193 - Tratar CHARSET em consultas com resultados com acentuação diferenciando o SGBD

- src/Pessoa.php
> Fix #195 - Adicionado Aluno Convênio Interc Grad no método Pessoa::tiposVinculos

- src/Pessoa.php
> Metódo que retorna data de nascimento

- README.md
> Explicando o método nascimento no README

- README.md
- src/Graduacao.php
- src/Pessoa.php
> Fix #197 - Obter vínculos e setores de uma pessoa

- README.md
- src/Lattes.php
>  Método que retorna ID Lattes e documentação

- src/Pessoa.php
> Padronização das queries para formato sem concatenação.

- src/Graduacao.php
> Fix #209 - Adicionados os créditos de trabalhos no métdodo Graduacao::disciplinasConcluidas

- README.md
- src/Pessoa.php
> Issue213: Metódo estágioUSP e documentação no README

- README.md
- src/Graduacao.php
- src/Pessoa.php
- test/functions.php
> Fix #217 Corrigindo consultas por gênero

- README.md
- src/Pessoa.php
> Resolve Issue 226

- doc/metodos_pessoa.md
- src/Pessoa.php
- test/functions.php
- test/pessoa/listarDocentes.php
- test/run.php
Fiz apenas para listar os docentes atuais mesmo. Para obter docentes senior o código será diferente, outro método.
Não consegui passar como parâmetro as variáveis na query, pois quando uso valors múltiplos, tanto pra unidade quanto para setores, separando por vírgula, dá erro que não consegui resolver.
> Fix issue #237

- doc/metodos_pessoa.md
apenas uma breve adição de uma informação que estava faltando
> Adicionando descrição do método telefones ao arquivo .md

- src/Pessoa.php
> Criado método para retornar ramal USP de um codpes.

- src/Posgraduacao.php
- tests/PosgraduacaoTest.php
- tests/schemas/AGPROGRAMA.sql
- tests/schemas/AREA.sql
- tests/schemas/CREDAREA.sql
- tests/schemas/DISCIPLINA.sql
- tests/schemas/ESPACOTURMA.sql
- tests/schemas/HISTPROGRAMA.sql
- tests/schemas/IDIOMA.sql
- tests/schemas/LOCALIZAPESSOA.sql
- tests/schemas/NOMEAREA.sql
- tests/schemas/OFERECIMENTO.sql
- tests/schemas/R32TURMINDOC.sql
- tests/schemas/TRABALHOPROG.sql
- tests/schemas/VINCULOPESSOAUSP.sql
@thiagogomesverissimo sei que você pediu um PR pra cada test, mas a função oferecimento() utilizava a função espacoturma() e ministrante() dentro dela, aí achei melhor já fazer as 3 juntas - até porque também só assim para o test funcionar rs.
> Posgraduacao - test_oferecimento()/test_espacoturma()/test_ministrante()

- doc/metodos_pessoa.md
- src/Pessoa.php
- tests/PessoaTest.php
- tests/schemas/CATR_CRACHA.sql
não consegui testar o método cracha com assertSame
> PessoaTest - método cracha

- src/Graduacao.php
- src/Pessoa.php
- tests/GraduacaoTest.php
- tests/PessoaTest.php
- tests/schemas/TITULOPES.sql
> Método verificarExAlunoGrad

- src/Lattes.php
> Método para retornar resumo do currículo na classe Lattes

- src/Lattes.php
> Livros publicados Lattes

- path/to/your.log
- src/Lattes.php
retorna os títulos de todas as linhas de pesquisa
> método getLinhasPesquisa feito 

- src/Graduacao.php
- tests/GraduacaoTest.php
Fix #319 
Verificação de status Conclusão por programa ou habilitação;
Adicionado código de teste novamente.
> Adicionado verificação por programa e habilitação.

- src/Lattes.php
> método getCapitulosLivros

- src/Posgraduacao.php
- tests/PosgraduacaoTest.php
> Correção teste obterOrientandosAtivos

- src/Lattes.php
- src/Posgraduacao.php
Lattes
Adição do método para pegar a última atualização do lattes, e implementando o parãmetro opcional do array do lattes, para não carregá-lo necessariamente toda hora.
PosGraduação
Permitindo a filtragem do programa atrravés do codare também.
> Ajustando dados para coletar informações para os programas(dados)

- resources/queries/Posgraduacao.obterOrientandosAtivos.sql
- resources/queries/Posgraduacao.obterOrientandosConcluidos.sql
- src/DB.php
- src/Posgraduacao.php
Deixando portanto o código PHP mais limpo
> Possibilidade de carregar a query de um arquivo sql

- resources/queries/Posgraduacao.listarDefesas.sql
- resources/queries/Posgraduacao.obterDefesas.sql
- src/Posgraduacao.php
> Criação de métodos para buscar defesas

- .travis.yml
- README.md
- composer.json
- src/DB.php
> Implementa suporte a biblioteca uspdev/cache de forma nativa

- src/Lattes.php
>  Complementando a parte de prefacio/posfacio em outras produções 

- src/Posgraduacao.php
fix #367 método a ser usado no sistema dados
> Fix #367 - Método obterAtivosPorArea

- src/Lattes.php
tentei seguir o padrão, porém fiquem a vontade para mudarem caso acharem que o método segue mais padrão X do que o que eu coloquei
> Métodos da classe Lattes renomeados

- src/Lattes.php
condição if para caso o egresso só tiver uma atuação profissional cadastrada no currículo lattes
> Melhoria no método listarFormacaoProfissional

- resources/queries/Posgraduacao.listarDefesas.sql
- resources/queries/Posgraduacao.obterDefesas.sql
defesas trazendo nomes repetidos
> Distinct adicionado nas querys de defesas

- src/Pessoa.php
Fix #384
Testado em uspdev/pessoas
> Fix #384 - Bug fix para aceitar chamada sem o código de unidade

- path/to/your.log
- src/Lattes.php
> Novo método listarRadioTV

- src/Pessoa.php
Fix #391
lista ou conta os servidores ativos do(s) setor(es)
inclui os aposentados e estagiários
exlcui os registros de designados
> Fix #391 - Novo método Pessoa::servidoresAtivosSetor

- src/Pessoa.php
Fix #391 
listarServidoresSetor
contarServidoresSetor
Ambos com a opção de excluir os Docentes Aposentados
> Fix #391 - Troca de nome do método e separados listar e contar

- README.md
- composer.json
- src/DB.php
> corrige problemas ao usar cache

- src/Beneficio.php
> listando beneficios concedidos

- resources/queries/Pessoa.listarFalecidosPorPeriodo.sql
- resources/queries/Pessoa.retornarFalecidosPorPeriodo.sql
- src/Pessoa.php
método para ser usado no site memorial fflch, a principio
> Método para retornar falecidos por período

- src/DB.php
> aplicando cache mais cedo pois nao melhorava desempenho

- resources/queries/Posgraduacao.listarOrientandosAtivos.sql
- src/Posgraduacao.php
Agora esse método chama o método obterVinculo para retornar mais informações a respeito do vinculo de pós graduação do orientando.
fix #424
> Alteração no método listarOrientandosAtivos

- src/Posgraduacao.php
if adicionado para verificar se o array está retornando algum vinculo, como solução, ao invés de passar o vínculo direto no array_merge, coloquei o vinculo em uma variável e fiz a verificação.
Fix #428
> Adicionando verificação no método listarOrientandosAtivos

- src/Posgraduacao.php
Foi preciso fazer uma verificação para ver se o array realmente estava retornando algum conteúdo.
> Verificação no array do método listarOrientandosAtivos

- src/DB.php
> Removendo utf8 da string de conexão

- src/Posgraduacao.php
> refatora metodo membrosBanca

- resources/queries/Graduacao.listarDisciplinasGradeCurricular.sql
- resources/queries/Pessoa.buscarICcomBolsaPorCodpes.sql
- resources/queries/Pessoa.buscarPDcomBolsaPorCodpes.sql
- resources/queries/Pessoa.listarFalecidosPorPeriodo.sql
- resources/queries/Pessoa.listarIniciaoCientificaAtiva.sql
- resources/queries/Pessoa.listarPesquisaPosDoutorandos.sql
- resources/queries/Pessoa.listarPesquisadoresColaboradoresAtivos.sql
- resources/queries/Pessoa.retornarCursoPorCodpes.sql
- resources/queries/Pessoa.retornarProgramaPorCodpes.sql
- resources/queries/Pessoa.retornarSupervisorPesquisaPosDoutorando.sql
- src/Pessoa.php
> deixando todo métodos genéricos para qualquer unidades

- resources/queries/Graduacao.listarIntercambios.sql
- src/Graduacao.php
> Método que lista intercâmbios ativos de alunos da graduação

- resources/queries/Graduacao.obterIntercambioPorCodpes.sql
- src/Graduacao.php
> Novo método obterIntercambioPorCodpes

- src/Pessoa.php
> ajustes da documentação docblock

- src/Lattes.php
> Corrigindo método listarApresentacaoTrabalho - classe Lattes

- src/Lattes.php
> Melhorando método listarCursosCurtaDuracao

- src/Pessoa.php
- src/Posgraduacao.php
> Transferindo o método totalPosNivelPrograma de Pessoa para Posgraduacao

- src/Pessoa.php
@thiagogomesverissimo e @masakik testem junto com a PR do uspdev/pessoas
> Fix #478 - Novo metodo listarMaisInformacoesServidores

- resources/queries/Graduacao.listarDisciplinasAlunoAnoSemestre.sql
- src/Graduacao.php
A ser usado num sistema de percepção institucional referente a disciplinas de graduação cursadas.
fix #482
> novo metodo listarDisciplinasAlunoAnoSemestre #482

- src/DB.php
- src/Pessoa.php
> refactor de sevidores para listarServidores #486

- src/Pessoa.php
> refactor do método procurarPorCodigoOuNome #488

- resources/queries/Graduacao.listarDisciplinasAlunoAnoSemestre.sql
- src/Graduacao.php
Fazendo o concat do ano/semestre no php ao invés da query.
fix #490
> Corrigindo compatibilidade do método listarDisciplinasAlunoAnoSemestre com o SQL Server 2008 #490

- resources/queries/Graduacao.listarDisciplinasAluno.sql
- resources/queries/Graduacao.listarDisciplinasAlunoAnoSemestre.sql
- resources/queries/Graduacao.obterMediaPonderada.sql
- src/Graduacao.php
e reaproveitando em obterMediaPonderada
fix #493
> novo método listarDisciplinasAluno #493

- src/Pessoa.php
> novo metodo listarVinculosAtivos #502

- src/Pessoa.php
> Fix 504 - Retonando a situação da vacina contra a covid19

- src/Graduacao.php
> issue #514

- resources/queries/Posgraduacao.listarDefesas.sql
- src/Posgraduacao.php
> Fixed #518 Posgraduacao::listarDefesas não filtra pelo código da unidade

- README.md
- resources/queries/Graduacao.obterCursoAtivo.sql
- resources/queries/Pessoa.contarServidoresSetor.sql
- resources/queries/Pessoa.listarDesignados.sql
- resources/queries/Pessoa.listarTiposVinculoExtenso.sql
- src/DB.php
- src/Graduacao.php
- src/Pessoa.php
Criando o PR para podermos ver o diff mais facilmente.
fix #524 fix #520 fix #521
Métodos
- Pessoa::listarVinculosSetores
- Pessoa::vinculosSetores - deprecado em favor de listarVinculosSetores
- Pessoa::listarDesignados
- Pessoa::contarServidoresSetor
- Pessoa::tiposVinculos
- Pessoa::ativosVinculo
- Pessoa::listarServidoresSetor
- Graduacao::curso
> Alecostaweb issue 520

- src/Graduacao.php
- src/Pessoa.php
Fix #520 
Método vinculosSetores
:+1:
> Considerando mais de um código de unidade

- src/Pessoa.php
Fix #528 
Método marcado como depreciado e aguardando momento oportuno para remover
> Método depreciado

- README.md
- composer.json
- src/Config.php
- src/DB.php
- src/Replicado.php
- src/Uteis.php
> Permite passar array de configuração para o replicado

- composer.json
> atualizando versões

- src/DB.php
- src/Replicado.php
> setar config do cache via configurador #534

- composer.json
> Alteração do illuminate/collections para Laravel 10

- resources/queries/Graduacao.listarDepartamentosDeEnsino.sql
- src/Graduacao.php
> Criando método listarDepartamentosDeEnsino

- resources/queries/Pessoa.listarTitulacoes.sql
- src/Pessoa.php
Fix #125 
Será utilizado no uspdev/pessoas
> Listar titulações de uma pessoa

- resources/queries/Pessoa.listarAfastados.sql
- src/Pessoa.php
> Listando servidores afastados

- resources/queries/Estrutura.obterUnidade.sql
- src/Estrutura.php
> Dados da unidade

- resources/queries/Pessoa.listarHistoricoFuncional.sql
- src/Pessoa.php
> Listar histórico funcional

- resources/queries/Pessoa.obterRamalUsp.sql
- src/Pessoa.php
> Corrigindo a consulta por Ramal USP

- src/Graduacao.php
Método contarAtivosPorGenero modificado
Fix #579
> Trocando a tabela SITALUNOATIVOGR por HABILPROGGR

- resources/queries/Beneficio.listarMonitoresProAluno.sql
- src/Beneficio.php
> Adiciona método para listar monitores da sala Pró-aluno
